[package]
name = "duna-macro"
version = "0.0.1"
authors = ["noloerino <jhshi07@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
